namespace Prototipo_Ana.Forms
{
    partial class Productos
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Productos));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.label7 = new System.Windows.Forms.Label();
            this.lblId = new System.Windows.Forms.Label();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblNombre = new System.Windows.Forms.Label();
            this.txtNombreMaterial = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.txtPrecio = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.cbmPrecio_GrupoR = new Bunifu.UI.WinForms.BunifuDropdown();
            this.label3 = new System.Windows.Forms.Label();
            this.button1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnGuardarClienteR = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnEditar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuVScrollBar2 = new Bunifu.UI.WinForms.BunifuVScrollBar();
            this.dtaProductos = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.txtFiltro = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnborrar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnlimpiar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.dtaProductos)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.label7.Location = new System.Drawing.Point(81, 656);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(79, 25);
            this.label7.TabIndex = 47;
            this.label7.Text = "Buscar";
            // 
            // lblId
            // 
            this.lblId.BackColor = System.Drawing.Color.White;
            this.lblId.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblId.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblId.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.lblId.Location = new System.Drawing.Point(943, 26);
            this.lblId.Name = "lblId";
            this.lblId.Size = new System.Drawing.Size(140, 25);
            this.lblId.TabIndex = 65;
            this.lblId.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblId.Visible = false;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Poppins", 16.2F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.bunifuLabel2.Location = new System.Drawing.Point(48, 26);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(149, 48);
            this.bunifuLabel2.TabIndex = 68;
            this.bunifuLabel2.Text = "Materiales";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblNombre
            // 
            this.lblNombre.Font = new System.Drawing.Font("Poppins", 13.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblNombre.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.lblNombre.Location = new System.Drawing.Point(46, 132);
            this.lblNombre.Name = "lblNombre";
            this.lblNombre.Size = new System.Drawing.Size(128, 33);
            this.lblNombre.TabIndex = 85;
            this.lblNombre.Text = "Nombre";
            // 
            // txtNombreMaterial
            // 
            this.txtNombreMaterial.AcceptsReturn = false;
            this.txtNombreMaterial.AcceptsTab = false;
            this.txtNombreMaterial.AnimationSpeed = 200;
            this.txtNombreMaterial.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNombreMaterial.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNombreMaterial.AutoSizeHeight = true;
            this.txtNombreMaterial.BackColor = System.Drawing.Color.Transparent;
            this.txtNombreMaterial.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNombreMaterial.BackgroundImage")));
            this.txtNombreMaterial.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNombreMaterial.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNombreMaterial.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNombreMaterial.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtNombreMaterial.BorderRadius = 20;
            this.txtNombreMaterial.BorderThickness = 1;
            this.txtNombreMaterial.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtNombreMaterial.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNombreMaterial.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombreMaterial.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNombreMaterial.DefaultText = "";
            this.txtNombreMaterial.FillColor = System.Drawing.Color.White;
            this.txtNombreMaterial.HideSelection = true;
            this.txtNombreMaterial.IconLeft = null;
            this.txtNombreMaterial.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombreMaterial.IconPadding = 10;
            this.txtNombreMaterial.IconRight = null;
            this.txtNombreMaterial.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombreMaterial.Lines = new string[0];
            this.txtNombreMaterial.Location = new System.Drawing.Point(48, 168);
            this.txtNombreMaterial.MaxLength = 32767;
            this.txtNombreMaterial.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNombreMaterial.Modified = false;
            this.txtNombreMaterial.Multiline = false;
            this.txtNombreMaterial.Name = "txtNombreMaterial";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombreMaterial.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNombreMaterial.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombreMaterial.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Transparent;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombreMaterial.OnIdleState = stateProperties4;
            this.txtNombreMaterial.Padding = new System.Windows.Forms.Padding(3);
            this.txtNombreMaterial.PasswordChar = '\0';
            this.txtNombreMaterial.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNombreMaterial.PlaceholderText = "";
            this.txtNombreMaterial.ReadOnly = false;
            this.txtNombreMaterial.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNombreMaterial.SelectedText = "";
            this.txtNombreMaterial.SelectionLength = 0;
            this.txtNombreMaterial.SelectionStart = 0;
            this.txtNombreMaterial.ShortcutsEnabled = true;
            this.txtNombreMaterial.Size = new System.Drawing.Size(318, 30);
            this.txtNombreMaterial.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNombreMaterial.TabIndex = 86;
            this.txtNombreMaterial.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNombreMaterial.TextMarginBottom = 0;
            this.txtNombreMaterial.TextMarginLeft = 3;
            this.txtNombreMaterial.TextMarginTop = 1;
            this.txtNombreMaterial.TextPlaceholder = "";
            this.txtNombreMaterial.UseSystemPasswordChar = false;
            this.txtNombreMaterial.WordWrap = true;
            // 
            // label4
            // 
            this.label4.Font = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.DimGray;
            this.label4.Location = new System.Drawing.Point(43, 87);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(224, 40);
            this.label4.TabIndex = 87;
            this.label4.Text = "Añade un material";
            // 
            // label2
            // 
            this.label2.Font = new System.Drawing.Font("Poppins", 13.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.label2.Location = new System.Drawing.Point(46, 257);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(128, 39);
            this.label2.TabIndex = 88;
            this.label2.Text = "Precio";
            this.label2.Visible = false;
            // 
            // txtPrecio
            // 
            this.txtPrecio.AcceptsReturn = false;
            this.txtPrecio.AcceptsTab = false;
            this.txtPrecio.AnimationSpeed = 200;
            this.txtPrecio.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPrecio.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPrecio.AutoSizeHeight = true;
            this.txtPrecio.BackColor = System.Drawing.Color.Transparent;
            this.txtPrecio.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPrecio.BackgroundImage")));
            this.txtPrecio.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPrecio.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPrecio.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPrecio.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtPrecio.BorderRadius = 20;
            this.txtPrecio.BorderThickness = 1;
            this.txtPrecio.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtPrecio.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPrecio.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrecio.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPrecio.DefaultText = "";
            this.txtPrecio.FillColor = System.Drawing.Color.White;
            this.txtPrecio.HideSelection = true;
            this.txtPrecio.IconLeft = null;
            this.txtPrecio.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrecio.IconPadding = 10;
            this.txtPrecio.IconRight = null;
            this.txtPrecio.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPrecio.Lines = new string[0];
            this.txtPrecio.Location = new System.Drawing.Point(48, 299);
            this.txtPrecio.MaxLength = 32767;
            this.txtPrecio.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPrecio.Modified = false;
            this.txtPrecio.Multiline = false;
            this.txtPrecio.Name = "txtPrecio";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrecio.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPrecio.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrecio.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Transparent;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPrecio.OnIdleState = stateProperties8;
            this.txtPrecio.Padding = new System.Windows.Forms.Padding(3);
            this.txtPrecio.PasswordChar = '\0';
            this.txtPrecio.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPrecio.PlaceholderText = "";
            this.txtPrecio.ReadOnly = false;
            this.txtPrecio.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPrecio.SelectedText = "";
            this.txtPrecio.SelectionLength = 0;
            this.txtPrecio.SelectionStart = 0;
            this.txtPrecio.ShortcutsEnabled = true;
            this.txtPrecio.Size = new System.Drawing.Size(219, 30);
            this.txtPrecio.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPrecio.TabIndex = 89;
            this.txtPrecio.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPrecio.TextMarginBottom = 0;
            this.txtPrecio.TextMarginLeft = 3;
            this.txtPrecio.TextMarginTop = 1;
            this.txtPrecio.TextPlaceholder = "";
            this.txtPrecio.UseSystemPasswordChar = false;
            this.txtPrecio.Visible = false;
            this.txtPrecio.WordWrap = true;
            // 
            // label6
            // 
            this.label6.Font = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.DimGray;
            this.label6.Location = new System.Drawing.Point(43, 221);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(224, 34);
            this.label6.TabIndex = 90;
            this.label6.Text = "Añadir precios";
            this.label6.Visible = false;
            // 
            // cbmPrecio_GrupoR
            // 
            this.cbmPrecio_GrupoR.BackColor = System.Drawing.Color.Transparent;
            this.cbmPrecio_GrupoR.BackgroundColor = System.Drawing.Color.White;
            this.cbmPrecio_GrupoR.BorderColor = System.Drawing.Color.Transparent;
            this.cbmPrecio_GrupoR.BorderRadius = 10;
            this.cbmPrecio_GrupoR.Color = System.Drawing.Color.Transparent;
            this.cbmPrecio_GrupoR.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbmPrecio_GrupoR.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbmPrecio_GrupoR.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cbmPrecio_GrupoR.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbmPrecio_GrupoR.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cbmPrecio_GrupoR.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cbmPrecio_GrupoR.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbmPrecio_GrupoR.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbmPrecio_GrupoR.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbmPrecio_GrupoR.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbmPrecio_GrupoR.FillDropDown = true;
            this.cbmPrecio_GrupoR.FillIndicator = false;
            this.cbmPrecio_GrupoR.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbmPrecio_GrupoR.Font = new System.Drawing.Font("Poppins", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cbmPrecio_GrupoR.ForeColor = System.Drawing.Color.Black;
            this.cbmPrecio_GrupoR.FormattingEnabled = true;
            this.cbmPrecio_GrupoR.Icon = null;
            this.cbmPrecio_GrupoR.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbmPrecio_GrupoR.IndicatorColor = System.Drawing.Color.DarkGray;
            this.cbmPrecio_GrupoR.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbmPrecio_GrupoR.IndicatorThickness = 2;
            this.cbmPrecio_GrupoR.IsDropdownOpened = false;
            this.cbmPrecio_GrupoR.ItemBackColor = System.Drawing.Color.White;
            this.cbmPrecio_GrupoR.ItemBorderColor = System.Drawing.Color.White;
            this.cbmPrecio_GrupoR.ItemForeColor = System.Drawing.Color.Black;
            this.cbmPrecio_GrupoR.ItemHeight = 17;
            this.cbmPrecio_GrupoR.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cbmPrecio_GrupoR.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cbmPrecio_GrupoR.Items.AddRange(new object[] {
            "Grupo 1",
            "Grupo 2",
            "Grupo 3",
            "Grupo 4"});
            this.cbmPrecio_GrupoR.ItemTopMargin = 3;
            this.cbmPrecio_GrupoR.Location = new System.Drawing.Point(275, 300);
            this.cbmPrecio_GrupoR.Name = "cbmPrecio_GrupoR";
            this.cbmPrecio_GrupoR.Size = new System.Drawing.Size(144, 23);
            this.cbmPrecio_GrupoR.TabIndex = 91;
            this.cbmPrecio_GrupoR.Text = null;
            this.cbmPrecio_GrupoR.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbmPrecio_GrupoR.TextLeftMargin = 5;
            this.cbmPrecio_GrupoR.Visible = false;
            // 
            // label3
            // 
            this.label3.Font = new System.Drawing.Font("Poppins", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.label3.Location = new System.Drawing.Point(277, 271);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(108, 27);
            this.label3.TabIndex = 92;
            this.label3.Text = "Grupo";
            this.label3.Visible = false;
            // 
            // button1
            // 
            this.button1.AllowAnimations = true;
            this.button1.AllowMouseEffects = true;
            this.button1.AllowToggling = false;
            this.button1.AnimationSpeed = 200;
            this.button1.AutoGenerateColors = false;
            this.button1.AutoRoundBorders = false;
            this.button1.AutoSizeLeftIcon = true;
            this.button1.AutoSizeRightIcon = true;
            this.button1.BackColor = System.Drawing.Color.Transparent;
            this.button1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.button1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button1.BackgroundImage")));
            this.button1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button1.ButtonText = "Guardar Material";
            this.button1.ButtonTextMarginLeft = 0;
            this.button1.ColorContrastOnClick = 45;
            this.button1.ColorContrastOnHover = 45;
            this.button1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.button1.CustomizableEdges = borderEdges1;
            this.button1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.button1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.button1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.button1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Disabled;
            this.button1.Font = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.button1.ForeColor = System.Drawing.Color.White;
            this.button1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.button1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.button1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.button1.IconMarginLeft = 11;
            this.button1.IconPadding = 10;
            this.button1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.button1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.button1.IconSize = 25;
            this.button1.IdleBorderColor = System.Drawing.Color.Transparent;
            this.button1.IdleBorderRadius = 20;
            this.button1.IdleBorderThickness = 1;
            this.button1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.button1.IdleIconLeftImage = null;
            this.button1.IdleIconRightImage = null;
            this.button1.IndicateFocus = false;
            this.button1.Location = new System.Drawing.Point(376, 168);
            this.button1.Name = "button1";
            this.button1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.button1.OnDisabledState.BorderRadius = 20;
            this.button1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button1.OnDisabledState.BorderThickness = 1;
            this.button1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.button1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.button1.OnDisabledState.IconLeftImage = null;
            this.button1.OnDisabledState.IconRightImage = null;
            this.button1.onHoverState.BorderColor = System.Drawing.Color.White;
            this.button1.onHoverState.BorderRadius = 20;
            this.button1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button1.onHoverState.BorderThickness = 1;
            this.button1.onHoverState.FillColor = System.Drawing.Color.White;
            this.button1.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.button1.onHoverState.IconLeftImage = null;
            this.button1.onHoverState.IconRightImage = null;
            this.button1.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.button1.OnIdleState.BorderRadius = 20;
            this.button1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button1.OnIdleState.BorderThickness = 1;
            this.button1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.button1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.button1.OnIdleState.IconLeftImage = null;
            this.button1.OnIdleState.IconRightImage = null;
            this.button1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.button1.OnPressedState.BorderRadius = 20;
            this.button1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.button1.OnPressedState.BorderThickness = 1;
            this.button1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.button1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.button1.OnPressedState.IconLeftImage = null;
            this.button1.OnPressedState.IconRightImage = null;
            this.button1.Size = new System.Drawing.Size(218, 30);
            this.button1.TabIndex = 93;
            this.button1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.button1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.button1.TextMarginLeft = 0;
            this.button1.TextPadding = new System.Windows.Forms.Padding(0);
            this.button1.UseDefaultRadiusAndThickness = true;
            this.button1.Click += new System.EventHandler(this.button1_Click_1);
            // 
            // btnGuardarClienteR
            // 
            this.btnGuardarClienteR.AllowAnimations = true;
            this.btnGuardarClienteR.AllowMouseEffects = true;
            this.btnGuardarClienteR.AllowToggling = false;
            this.btnGuardarClienteR.AnimationSpeed = 200;
            this.btnGuardarClienteR.AutoGenerateColors = false;
            this.btnGuardarClienteR.AutoRoundBorders = false;
            this.btnGuardarClienteR.AutoSizeLeftIcon = true;
            this.btnGuardarClienteR.AutoSizeRightIcon = true;
            this.btnGuardarClienteR.BackColor = System.Drawing.Color.Transparent;
            this.btnGuardarClienteR.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnGuardarClienteR.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGuardarClienteR.BackgroundImage")));
            this.btnGuardarClienteR.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardarClienteR.ButtonText = "Guardar";
            this.btnGuardarClienteR.ButtonTextMarginLeft = 0;
            this.btnGuardarClienteR.ColorContrastOnClick = 45;
            this.btnGuardarClienteR.ColorContrastOnHover = 45;
            this.btnGuardarClienteR.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnGuardarClienteR.CustomizableEdges = borderEdges2;
            this.btnGuardarClienteR.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGuardarClienteR.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGuardarClienteR.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGuardarClienteR.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGuardarClienteR.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Disabled;
            this.btnGuardarClienteR.Font = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnGuardarClienteR.ForeColor = System.Drawing.Color.White;
            this.btnGuardarClienteR.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGuardarClienteR.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnGuardarClienteR.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnGuardarClienteR.IconMarginLeft = 11;
            this.btnGuardarClienteR.IconPadding = 10;
            this.btnGuardarClienteR.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGuardarClienteR.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnGuardarClienteR.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnGuardarClienteR.IconSize = 25;
            this.btnGuardarClienteR.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnGuardarClienteR.IdleBorderRadius = 20;
            this.btnGuardarClienteR.IdleBorderThickness = 1;
            this.btnGuardarClienteR.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnGuardarClienteR.IdleIconLeftImage = null;
            this.btnGuardarClienteR.IdleIconRightImage = null;
            this.btnGuardarClienteR.IndicateFocus = false;
            this.btnGuardarClienteR.Location = new System.Drawing.Point(433, 297);
            this.btnGuardarClienteR.Name = "btnGuardarClienteR";
            this.btnGuardarClienteR.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGuardarClienteR.OnDisabledState.BorderRadius = 20;
            this.btnGuardarClienteR.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardarClienteR.OnDisabledState.BorderThickness = 1;
            this.btnGuardarClienteR.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGuardarClienteR.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGuardarClienteR.OnDisabledState.IconLeftImage = null;
            this.btnGuardarClienteR.OnDisabledState.IconRightImage = null;
            this.btnGuardarClienteR.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnGuardarClienteR.onHoverState.BorderRadius = 20;
            this.btnGuardarClienteR.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardarClienteR.onHoverState.BorderThickness = 1;
            this.btnGuardarClienteR.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnGuardarClienteR.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnGuardarClienteR.onHoverState.IconLeftImage = null;
            this.btnGuardarClienteR.onHoverState.IconRightImage = null;
            this.btnGuardarClienteR.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnGuardarClienteR.OnIdleState.BorderRadius = 20;
            this.btnGuardarClienteR.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardarClienteR.OnIdleState.BorderThickness = 1;
            this.btnGuardarClienteR.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnGuardarClienteR.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnGuardarClienteR.OnIdleState.IconLeftImage = null;
            this.btnGuardarClienteR.OnIdleState.IconRightImage = null;
            this.btnGuardarClienteR.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnGuardarClienteR.OnPressedState.BorderRadius = 20;
            this.btnGuardarClienteR.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardarClienteR.OnPressedState.BorderThickness = 1;
            this.btnGuardarClienteR.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnGuardarClienteR.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnGuardarClienteR.OnPressedState.IconLeftImage = null;
            this.btnGuardarClienteR.OnPressedState.IconRightImage = null;
            this.btnGuardarClienteR.Size = new System.Drawing.Size(161, 30);
            this.btnGuardarClienteR.TabIndex = 94;
            this.btnGuardarClienteR.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnGuardarClienteR.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnGuardarClienteR.TextMarginLeft = 0;
            this.btnGuardarClienteR.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnGuardarClienteR.UseDefaultRadiusAndThickness = true;
            this.btnGuardarClienteR.Visible = false;
            this.btnGuardarClienteR.Click += new System.EventHandler(this.btnGuardarClienteR_Click);
            // 
            // btnEditar
            // 
            this.btnEditar.AllowAnimations = true;
            this.btnEditar.AllowMouseEffects = true;
            this.btnEditar.AllowToggling = false;
            this.btnEditar.AnimationSpeed = 200;
            this.btnEditar.AutoGenerateColors = false;
            this.btnEditar.AutoRoundBorders = false;
            this.btnEditar.AutoSizeLeftIcon = true;
            this.btnEditar.AutoSizeRightIcon = true;
            this.btnEditar.BackColor = System.Drawing.Color.Transparent;
            this.btnEditar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnEditar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEditar.BackgroundImage")));
            this.btnEditar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEditar.ButtonText = "Editar";
            this.btnEditar.ButtonTextMarginLeft = 0;
            this.btnEditar.ColorContrastOnClick = 45;
            this.btnEditar.ColorContrastOnHover = 45;
            this.btnEditar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnEditar.CustomizableEdges = borderEdges3;
            this.btnEditar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEditar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEditar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEditar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEditar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Disabled;
            this.btnEditar.Font = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEditar.ForeColor = System.Drawing.Color.White;
            this.btnEditar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEditar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEditar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEditar.IconMarginLeft = 11;
            this.btnEditar.IconPadding = 10;
            this.btnEditar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEditar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEditar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEditar.IconSize = 25;
            this.btnEditar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnEditar.IdleBorderRadius = 20;
            this.btnEditar.IdleBorderThickness = 1;
            this.btnEditar.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnEditar.IdleIconLeftImage = null;
            this.btnEditar.IdleIconRightImage = null;
            this.btnEditar.IndicateFocus = false;
            this.btnEditar.Location = new System.Drawing.Point(550, 405);
            this.btnEditar.Name = "btnEditar";
            this.btnEditar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEditar.OnDisabledState.BorderRadius = 20;
            this.btnEditar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEditar.OnDisabledState.BorderThickness = 1;
            this.btnEditar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEditar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEditar.OnDisabledState.IconLeftImage = null;
            this.btnEditar.OnDisabledState.IconRightImage = null;
            this.btnEditar.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnEditar.onHoverState.BorderRadius = 20;
            this.btnEditar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEditar.onHoverState.BorderThickness = 1;
            this.btnEditar.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnEditar.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnEditar.onHoverState.IconLeftImage = null;
            this.btnEditar.onHoverState.IconRightImage = null;
            this.btnEditar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnEditar.OnIdleState.BorderRadius = 20;
            this.btnEditar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEditar.OnIdleState.BorderThickness = 1;
            this.btnEditar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnEditar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEditar.OnIdleState.IconLeftImage = null;
            this.btnEditar.OnIdleState.IconRightImage = null;
            this.btnEditar.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnEditar.OnPressedState.BorderRadius = 20;
            this.btnEditar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEditar.OnPressedState.BorderThickness = 1;
            this.btnEditar.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnEditar.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.btnEditar.OnPressedState.IconLeftImage = null;
            this.btnEditar.OnPressedState.IconRightImage = null;
            this.btnEditar.Size = new System.Drawing.Size(119, 29);
            this.btnEditar.TabIndex = 95;
            this.btnEditar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEditar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEditar.TextMarginLeft = 0;
            this.btnEditar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEditar.UseDefaultRadiusAndThickness = true;
            this.btnEditar.Click += new System.EventHandler(this.btnEditar_Click_1);
            // 
            // bunifuVScrollBar2
            // 
            this.bunifuVScrollBar2.AllowCursorChanges = true;
            this.bunifuVScrollBar2.AllowHomeEndKeysDetection = false;
            this.bunifuVScrollBar2.AllowIncrementalClickMoves = true;
            this.bunifuVScrollBar2.AllowMouseDownEffects = true;
            this.bunifuVScrollBar2.AllowMouseHoverEffects = true;
            this.bunifuVScrollBar2.AllowScrollingAnimations = true;
            this.bunifuVScrollBar2.AllowScrollKeysDetection = true;
            this.bunifuVScrollBar2.AllowScrollOptionsMenu = true;
            this.bunifuVScrollBar2.AllowShrinkingOnFocusLost = false;
            this.bunifuVScrollBar2.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(236)))), ((int)(((byte)(236)))));
            this.bunifuVScrollBar2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuVScrollBar2.BackgroundImage")));
            this.bunifuVScrollBar2.BindingContainer = null;
            this.bunifuVScrollBar2.BorderColor = System.Drawing.Color.Silver;
            this.bunifuVScrollBar2.BorderRadius = 6;
            this.bunifuVScrollBar2.BorderThickness = 2;
            this.bunifuVScrollBar2.DurationBeforeShrink = 2000;
            this.bunifuVScrollBar2.LargeChange = 17;
            this.bunifuVScrollBar2.Location = new System.Drawing.Point(1176, 520);
            this.bunifuVScrollBar2.Maximum = 100;
            this.bunifuVScrollBar2.Minimum = 0;
            this.bunifuVScrollBar2.MinimumThumbLength = 18;
            this.bunifuVScrollBar2.Name = "bunifuVScrollBar2";
            this.bunifuVScrollBar2.OnDisable.ScrollBarBorderColor = System.Drawing.Color.Silver;
            this.bunifuVScrollBar2.OnDisable.ScrollBarColor = System.Drawing.Color.Transparent;
            this.bunifuVScrollBar2.OnDisable.ThumbColor = System.Drawing.Color.Silver;
            this.bunifuVScrollBar2.ScrollBarBorderColor = System.Drawing.Color.Silver;
            this.bunifuVScrollBar2.ScrollBarColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(236)))), ((int)(((byte)(236)))));
            this.bunifuVScrollBar2.ShrinkSizeLimit = 3;
            this.bunifuVScrollBar2.Size = new System.Drawing.Size(30, 187);
            this.bunifuVScrollBar2.SmallChange = 1;
            this.bunifuVScrollBar2.TabIndex = 97;
            this.bunifuVScrollBar2.ThumbColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.bunifuVScrollBar2.ThumbLength = 30;
            this.bunifuVScrollBar2.ThumbMargin = 1;
            this.bunifuVScrollBar2.ThumbStyle = Bunifu.UI.WinForms.BunifuVScrollBar.ThumbStyles.Inset;
            this.bunifuVScrollBar2.Value = 0;
            this.bunifuVScrollBar2.Scroll += new System.EventHandler<Bunifu.UI.WinForms.BunifuVScrollBar.ScrollEventArgs>(this.bunifuVScrollBar2_Scroll);
            // 
            // dtaProductos
            // 
            this.dtaProductos.AllowCustomTheming = false;
            this.dtaProductos.AllowUserToAddRows = false;
            this.dtaProductos.AllowUserToDeleteRows = false;
            this.dtaProductos.AllowUserToResizeColumns = false;
            this.dtaProductos.AllowUserToResizeRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dtaProductos.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dtaProductos.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dtaProductos.BackgroundColor = System.Drawing.Color.White;
            this.dtaProductos.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dtaProductos.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dtaProductos.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dtaProductos.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dtaProductos.ColumnHeadersHeight = 40;
            this.dtaProductos.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dtaProductos.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtaProductos.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtaProductos.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtaProductos.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dtaProductos.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dtaProductos.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtaProductos.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dtaProductos.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dtaProductos.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dtaProductos.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dtaProductos.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dtaProductos.CurrentTheme.Name = null;
            this.dtaProductos.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dtaProductos.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtaProductos.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtaProductos.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtaProductos.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dtaProductos.DefaultCellStyle = dataGridViewCellStyle3;
            this.dtaProductos.EnableHeadersVisualStyles = false;
            this.dtaProductos.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtaProductos.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dtaProductos.HeaderBgColor = System.Drawing.Color.Empty;
            this.dtaProductos.HeaderForeColor = System.Drawing.Color.White;
            this.dtaProductos.Location = new System.Drawing.Point(48, 462);
            this.dtaProductos.Name = "dtaProductos";
            this.dtaProductos.ReadOnly = true;
            this.dtaProductos.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(236)))), ((int)(((byte)(236)))));
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Poppins", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(236)))), ((int)(((byte)(236)))));
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dtaProductos.RowHeadersDefaultCellStyle = dataGridViewCellStyle4;
            this.dtaProductos.RowHeadersVisible = false;
            this.dtaProductos.RowHeadersWidth = 51;
            this.dtaProductos.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Poppins", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            this.dtaProductos.RowsDefaultCellStyle = dataGridViewCellStyle5;
            this.dtaProductos.RowTemplate.Height = 40;
            this.dtaProductos.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.dtaProductos.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dtaProductos.Size = new System.Drawing.Size(1126, 245);
            this.dtaProductos.TabIndex = 96;
            this.dtaProductos.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // txtFiltro
            // 
            this.txtFiltro.AcceptsReturn = false;
            this.txtFiltro.AcceptsTab = false;
            this.txtFiltro.AnimationSpeed = 200;
            this.txtFiltro.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtFiltro.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtFiltro.AutoSizeHeight = true;
            this.txtFiltro.BackColor = System.Drawing.Color.Transparent;
            this.txtFiltro.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtFiltro.BackgroundImage")));
            this.txtFiltro.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtFiltro.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtFiltro.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtFiltro.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtFiltro.BorderRadius = 20;
            this.txtFiltro.BorderThickness = 1;
            this.txtFiltro.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtFiltro.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtFiltro.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFiltro.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtFiltro.DefaultText = "";
            this.txtFiltro.FillColor = System.Drawing.Color.White;
            this.txtFiltro.HideSelection = true;
            this.txtFiltro.IconLeft = null;
            this.txtFiltro.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFiltro.IconPadding = 10;
            this.txtFiltro.IconRight = null;
            this.txtFiltro.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFiltro.Lines = new string[0];
            this.txtFiltro.Location = new System.Drawing.Point(48, 397);
            this.txtFiltro.MaxLength = 32767;
            this.txtFiltro.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtFiltro.Modified = false;
            this.txtFiltro.Multiline = false;
            this.txtFiltro.Name = "txtFiltro";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFiltro.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtFiltro.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFiltro.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Transparent;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFiltro.OnIdleState = stateProperties12;
            this.txtFiltro.Padding = new System.Windows.Forms.Padding(3);
            this.txtFiltro.PasswordChar = '\0';
            this.txtFiltro.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtFiltro.PlaceholderText = "Buscar";
            this.txtFiltro.ReadOnly = false;
            this.txtFiltro.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtFiltro.SelectedText = "";
            this.txtFiltro.SelectionLength = 0;
            this.txtFiltro.SelectionStart = 0;
            this.txtFiltro.ShortcutsEnabled = true;
            this.txtFiltro.Size = new System.Drawing.Size(496, 38);
            this.txtFiltro.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtFiltro.TabIndex = 98;
            this.txtFiltro.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtFiltro.TextMarginBottom = 0;
            this.txtFiltro.TextMarginLeft = 3;
            this.txtFiltro.TextMarginTop = 1;
            this.txtFiltro.TextPlaceholder = "Buscar";
            this.txtFiltro.UseSystemPasswordChar = false;
            this.txtFiltro.WordWrap = true;
            this.txtFiltro.TextChanged += new System.EventHandler(this.txtFiltro_TextChanged_1);
            // 
            // btnborrar
            // 
            this.btnborrar.AllowAnimations = true;
            this.btnborrar.AllowMouseEffects = true;
            this.btnborrar.AllowToggling = false;
            this.btnborrar.AnimationSpeed = 200;
            this.btnborrar.AutoGenerateColors = false;
            this.btnborrar.AutoRoundBorders = false;
            this.btnborrar.AutoSizeLeftIcon = true;
            this.btnborrar.AutoSizeRightIcon = true;
            this.btnborrar.BackColor = System.Drawing.Color.Transparent;
            this.btnborrar.BackColor1 = System.Drawing.Color.Red;
            this.btnborrar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnborrar.BackgroundImage")));
            this.btnborrar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnborrar.ButtonText = "Borrar";
            this.btnborrar.ButtonTextMarginLeft = 0;
            this.btnborrar.ColorContrastOnClick = 45;
            this.btnborrar.ColorContrastOnHover = 45;
            this.btnborrar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnborrar.CustomizableEdges = borderEdges4;
            this.btnborrar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnborrar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnborrar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnborrar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnborrar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Disabled;
            this.btnborrar.Font = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnborrar.ForeColor = System.Drawing.Color.White;
            this.btnborrar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnborrar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnborrar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnborrar.IconMarginLeft = 11;
            this.btnborrar.IconPadding = 10;
            this.btnborrar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnborrar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnborrar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnborrar.IconSize = 25;
            this.btnborrar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnborrar.IdleBorderRadius = 20;
            this.btnborrar.IdleBorderThickness = 1;
            this.btnborrar.IdleFillColor = System.Drawing.Color.Red;
            this.btnborrar.IdleIconLeftImage = null;
            this.btnborrar.IdleIconRightImage = null;
            this.btnborrar.IndicateFocus = false;
            this.btnborrar.Location = new System.Drawing.Point(702, 406);
            this.btnborrar.Name = "btnborrar";
            this.btnborrar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnborrar.OnDisabledState.BorderRadius = 20;
            this.btnborrar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnborrar.OnDisabledState.BorderThickness = 1;
            this.btnborrar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnborrar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnborrar.OnDisabledState.IconLeftImage = null;
            this.btnborrar.OnDisabledState.IconRightImage = null;
            this.btnborrar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnborrar.onHoverState.BorderRadius = 20;
            this.btnborrar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnborrar.onHoverState.BorderThickness = 1;
            this.btnborrar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnborrar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnborrar.onHoverState.IconLeftImage = null;
            this.btnborrar.onHoverState.IconRightImage = null;
            this.btnborrar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnborrar.OnIdleState.BorderRadius = 20;
            this.btnborrar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnborrar.OnIdleState.BorderThickness = 1;
            this.btnborrar.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.btnborrar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnborrar.OnIdleState.IconLeftImage = null;
            this.btnborrar.OnIdleState.IconRightImage = null;
            this.btnborrar.OnPressedState.BorderColor = System.Drawing.Color.Red;
            this.btnborrar.OnPressedState.BorderRadius = 20;
            this.btnborrar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnborrar.OnPressedState.BorderThickness = 1;
            this.btnborrar.OnPressedState.FillColor = System.Drawing.Color.Red;
            this.btnborrar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnborrar.OnPressedState.IconLeftImage = null;
            this.btnborrar.OnPressedState.IconRightImage = null;
            this.btnborrar.Size = new System.Drawing.Size(119, 29);
            this.btnborrar.TabIndex = 99;
            this.btnborrar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnborrar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnborrar.TextMarginLeft = 0;
            this.btnborrar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnborrar.UseDefaultRadiusAndThickness = true;
            this.btnborrar.Click += new System.EventHandler(this.btnborrar_Click);
            // 
            // btnlimpiar
            // 
            this.btnlimpiar.AllowAnimations = true;
            this.btnlimpiar.AllowMouseEffects = true;
            this.btnlimpiar.AllowToggling = false;
            this.btnlimpiar.AnimationSpeed = 200;
            this.btnlimpiar.AutoGenerateColors = false;
            this.btnlimpiar.AutoRoundBorders = false;
            this.btnlimpiar.AutoSizeLeftIcon = true;
            this.btnlimpiar.AutoSizeRightIcon = true;
            this.btnlimpiar.BackColor = System.Drawing.Color.Transparent;
            this.btnlimpiar.BackColor1 = System.Drawing.Color.White;
            this.btnlimpiar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnlimpiar.BackgroundImage")));
            this.btnlimpiar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnlimpiar.ButtonText = "Limpiar";
            this.btnlimpiar.ButtonTextMarginLeft = 0;
            this.btnlimpiar.ColorContrastOnClick = 45;
            this.btnlimpiar.ColorContrastOnHover = 45;
            this.btnlimpiar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnlimpiar.CustomizableEdges = borderEdges5;
            this.btnlimpiar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnlimpiar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnlimpiar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnlimpiar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnlimpiar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Disabled;
            this.btnlimpiar.Font = new System.Drawing.Font("Poppins", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnlimpiar.ForeColor = System.Drawing.Color.DimGray;
            this.btnlimpiar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnlimpiar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnlimpiar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnlimpiar.IconMarginLeft = 11;
            this.btnlimpiar.IconPadding = 10;
            this.btnlimpiar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnlimpiar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnlimpiar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnlimpiar.IconSize = 25;
            this.btnlimpiar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnlimpiar.IdleBorderRadius = 20;
            this.btnlimpiar.IdleBorderThickness = 1;
            this.btnlimpiar.IdleFillColor = System.Drawing.Color.White;
            this.btnlimpiar.IdleIconLeftImage = null;
            this.btnlimpiar.IdleIconRightImage = null;
            this.btnlimpiar.IndicateFocus = false;
            this.btnlimpiar.Location = new System.Drawing.Point(550, 362);
            this.btnlimpiar.Name = "btnlimpiar";
            this.btnlimpiar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnlimpiar.OnDisabledState.BorderRadius = 20;
            this.btnlimpiar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnlimpiar.OnDisabledState.BorderThickness = 1;
            this.btnlimpiar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnlimpiar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnlimpiar.OnDisabledState.IconLeftImage = null;
            this.btnlimpiar.OnDisabledState.IconRightImage = null;
            this.btnlimpiar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(170)))), ((int)(((byte)(170)))));
            this.btnlimpiar.onHoverState.BorderRadius = 20;
            this.btnlimpiar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnlimpiar.onHoverState.BorderThickness = 1;
            this.btnlimpiar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(170)))), ((int)(((byte)(170)))));
            this.btnlimpiar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnlimpiar.onHoverState.IconLeftImage = null;
            this.btnlimpiar.onHoverState.IconRightImage = null;
            this.btnlimpiar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnlimpiar.OnIdleState.BorderRadius = 20;
            this.btnlimpiar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnlimpiar.OnIdleState.BorderThickness = 1;
            this.btnlimpiar.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnlimpiar.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.btnlimpiar.OnIdleState.IconLeftImage = null;
            this.btnlimpiar.OnIdleState.IconRightImage = null;
            this.btnlimpiar.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnlimpiar.OnPressedState.BorderRadius = 20;
            this.btnlimpiar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnlimpiar.OnPressedState.BorderThickness = 1;
            this.btnlimpiar.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnlimpiar.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.btnlimpiar.OnPressedState.IconLeftImage = null;
            this.btnlimpiar.OnPressedState.IconRightImage = null;
            this.btnlimpiar.Size = new System.Drawing.Size(119, 29);
            this.btnlimpiar.TabIndex = 100;
            this.btnlimpiar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnlimpiar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnlimpiar.TextMarginLeft = 0;
            this.btnlimpiar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnlimpiar.UseDefaultRadiusAndThickness = true;
            this.btnlimpiar.Click += new System.EventHandler(this.btnlimpiar_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.White;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(502, 407);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(22, 19);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 101;
            this.pictureBox1.TabStop = false;
            // 
            // Productos
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(236)))), ((int)(((byte)(236)))));
            this.ClientSize = new System.Drawing.Size(1604, 739);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.btnlimpiar);
            this.Controls.Add(this.btnborrar);
            this.Controls.Add(this.txtFiltro);
            this.Controls.Add(this.bunifuVScrollBar2);
            this.Controls.Add(this.dtaProductos);
            this.Controls.Add(this.btnEditar);
            this.Controls.Add(this.btnGuardarClienteR);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.cbmPrecio_GrupoR);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.txtPrecio);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.txtNombreMaterial);
            this.Controls.Add(this.lblNombre);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.lblId);
            this.Controls.Add(this.label7);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Productos";
            this.Text = "Productos";
            this.Load += new System.EventHandler(this.Productos_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dtaProductos)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label lblId;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private System.Windows.Forms.Label lblNombre;
        private Bunifu.UI.WinForms.BunifuTextBox txtNombreMaterial;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox txtPrecio;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuDropdown cbmPrecio_GrupoR;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 button1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnGuardarClienteR;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnEditar;
        private Bunifu.UI.WinForms.BunifuVScrollBar bunifuVScrollBar2;
        private Bunifu.UI.WinForms.BunifuDataGridView dtaProductos;
        private Bunifu.UI.WinForms.BunifuTextBox txtFiltro;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnborrar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnlimpiar;
        private System.Windows.Forms.PictureBox pictureBox1;
    }
}